old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        billing:
            connection:       default
            exchange_options: { name: 'billing', type: topic }
    consumers:
        billing_deposit:
            connection:       default
            exchange_options: { name: 'billing', type: topic }
            queue_options:
                name: billing_deposit
                routing_keys:
                    - 'deposit'
            callback: app.consumer.deposit_operation
        billing_debit:
            connection:       default
            exchange_options: { name: 'billing', type: topic }
            queue_options:
                name: billing_debit
                routing_keys:
                    - 'debit'
            callback: app.consumer.debit_operation
        billing_transfer:
            connection:       default
            exchange_options: { name: 'billing', type: topic }
            queue_options:
                name: billing_transfer
                routing_keys:
                    - 'transfer'
            callback: app.consumer.transfer_operation
        billing_block:
            connection:       default
            exchange_options: { name: 'billing', type: topic }
            queue_options:
                name: billing_block
                routing_keys:
                    - 'block'
            callback: app.consumer.block_operation